language: julia
os:
  - linux
  - osx
julia:
  - release
  - nightly

sudo: false

# uncomment the following lines to override the default test script
#script:
#  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
#  - julia --check-bounds=yes -e 'Pkg.clone(pwd()); Pkg.build("TimeTree"); Pkg.test("TimeTree"; coverage=true)'
